### ISSUE TITLE
How do you apply the settings (How to enable/disable support for html)

### ISSUE THREAD

**Issue by izznogooood** [douglaszaltron/nunjucks-vscode-extensionpack#1]
With this installed all the "default" emmet abbreviatrion's for html disapears. Yes theres a settings.json example but how do I apply them? What object in the settings.json do I put them under.

Can I get HTML & NJK abbreviatrion's in the same file?

**Comment by weaversam8** [comment]
@izznogooood you don't need to put them under any object... you can simply insert each key as root key in settings.json...

For example, my settings.json now looks like this:
```js
{
    // existing settings.json keys
    // [...]
    //

    "html.suggest.html5": true,
    "emmet.includeLanguages": {
        "njk": "html"
    },
    "files.associations": {
        "*.njk": "njk"
    }
}
```

**Comment by izznogooood** [comment]
Yeah I figured that out, thanks for the follow-up 👍
